"""Generic remote-runtime environment configuration with legacy aliases."""

from __future__ import annotations

import os

LEGACY_CLIENT_CERT_HEADER = "X-M6-Client-Cert-SHA256"
CLIENT_CERT_HEADER = "X-Agentic-Client-Cert-SHA256"


LEGACY_ENVIRONMENT_NAMES = {
    "AGENTIC_RUNTIME_CONTROL_DATABASE_URL": "M5_CONTROL_DATABASE_URL",
    "AGENTIC_RUNTIME_ARTIFACT_ROOT": "M5_ARTIFACT_ROOT",
    "AGENTIC_RUNTIME_CONTROL_DATABASE_ROLE": "M5_CONTROL_DATABASE_ROLE",
    "AGENTIC_RUNTIME_LEASE_SECONDS": "M5_LEASE_SECONDS",
    "AGENTIC_RUNTIME_HEARTBEAT_SUSPECT_SECONDS": "M5_HEARTBEAT_SUSPECT_SECONDS",
    "AGENTIC_RUNTIME_CONTROL_ADMIN_TOKEN": "M5_CONTROL_ADMIN_TOKEN",
    "AGENTIC_RUNTIME_CONTROL_HOST": "M6_LISTEN_HOST",
    "AGENTIC_RUNTIME_CONTROL_HOST_LEGACY": "M5_LISTEN_HOST",
    "AGENTIC_RUNTIME_CONTROL_PORT": "M6_LISTEN_PORT",
    "AGENTIC_RUNTIME_CONTROL_PORT_LEGACY": "M5_LISTEN_PORT",
    "AGENTIC_RUNTIME_MAX_CONNECTIONS": "M6_MAX_CONNECTIONS",
    "AGENTIC_RUNTIME_MAINTENANCE_INTERVAL_SECONDS": "M6_MAINTENANCE_INTERVAL_SECONDS",
    "AGENTIC_RUNTIME_LOG_LEVEL": "M6_LOG_LEVEL",
    "AGENTIC_RUNTIME_TLS_CERT_FILE": "M6_TLS_CERT_FILE",
    "AGENTIC_RUNTIME_TLS_KEY_FILE": "M6_TLS_KEY_FILE",
    "AGENTIC_RUNTIME_TLS_CLIENT_CA_FILE": "M6_TLS_CLIENT_CA_FILE",
    "AGENTIC_RUNTIME_TLS_CA_FILE": "M6_TLS_CA_FILE",
    "AGENTIC_RUNTIME_REQUIRE_TLS": "M6_REQUIRE_TLS",
    "AGENTIC_RUNTIME_CONTROL_ENDPOINT": "M5_CONTROL_ENDPOINT",
    "AGENTIC_RUNTIME_WORKER_ID": "M5_WORKER_ID",
    "AGENTIC_RUNTIME_WORKER_TOKEN": "M5_WORKER_TOKEN",
    "AGENTIC_RUNTIME_WORKER_ROOT": "M5_WORKER_ROOT",
    "AGENTIC_RUNTIME_WORKER_CAPABILITIES": "M5_WORKER_CAPABILITIES",
    "AGENTIC_RUNTIME_WORKER_TASK_TYPES": "M5_WORKER_TASK_TYPES",
    "AGENTIC_RUNTIME_WORKER_RESOURCE_CLASSES": "M5_WORKER_RESOURCE_CLASSES",
    "AGENTIC_RUNTIME_WORKER_ALLOWED_TOOLS": "M5_WORKER_ALLOWED_TOOLS",
    "AGENTIC_RUNTIME_WORKER_RESOURCE_POLICY": "M5_WORKER_RESOURCE_POLICY",
    "AGENTIC_RUNTIME_WORKER_CLASS": "M6_WORKER_CLASS",
    "AGENTIC_RUNTIME_WORKER_ONCE": "M5_WORKER_ONCE",
}


def setting(name: str, default: str | None = None, *, required: bool = False) -> str | None:
    """Read a generic setting, falling back to a documented legacy alias."""
    value = os.environ.get(name)
    if value is None:
        legacy = LEGACY_ENVIRONMENT_NAMES.get(name)
        value = os.environ.get(legacy) if legacy else None
    if required and value is None:
        raise KeyError(name)
    return value if value is not None else default
