-- An expired RUNNING attempt may be moved to RETRY_PENDING only after its
-- lease has been fenced as EXPIRED in the same transaction.
CREATE OR REPLACE FUNCTION runtime.validate_task_transition() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE ok boolean := false;
BEGIN
    IF TG_OP='INSERT' THEN
        IF NEW.status NOT IN ('DRAFT','QUEUED') THEN
            RAISE EXCEPTION 'tasks must be created in DRAFT or QUEUED';
        END IF;
        RETURN NEW;
    END IF;
    IF OLD.status=NEW.status THEN RETURN NEW; END IF;
    ok := CASE OLD.status
        WHEN 'DRAFT' THEN NEW.status IN ('QUEUED','CANCELLED')
        WHEN 'QUEUED' THEN NEW.status IN ('LEASED','CANCELLED','BUDGET_EXCEEDED')
        WHEN 'RETRY_PENDING' THEN NEW.status IN ('LEASED','CANCELLED','BUDGET_EXCEEDED')
        WHEN 'LEASED' THEN NEW.status IN ('CONTEXT_VALIDATED','RUNNING','CANCELLED','FAILED_TRANSIENT','FAILED_PERMANENT','RETRY_PENDING')
        WHEN 'CONTEXT_VALIDATED' THEN NEW.status IN ('RUNNING','CANCELLED','FAILED_TRANSIENT','FAILED_PERMANENT')
        WHEN 'RUNNING' THEN NEW.status IN ('WAITING_CHILDREN','WAITING_TOOL','WAITING_IO','BLOCKED','CHECKPOINTED','RESULT_COMMITTED','NEEDS_REVIEW','FAILED_TRANSIENT','FAILED_PERMANENT','CANCELLED','BUDGET_EXCEEDED','QUARANTINED')
          OR (NEW.status='RETRY_PENDING' AND EXISTS (
              SELECT 1 FROM runtime.leases l WHERE l.task_id=OLD.task_id
                AND l.lease_epoch=OLD.lease_epoch AND l.status='EXPIRED'))
        WHEN 'WAITING_CHILDREN' THEN NEW.status IN ('QUEUED','RUNNING','BLOCKED','CANCELLED')
        WHEN 'WAITING_TOOL' THEN NEW.status IN ('RUNNING','BLOCKED','CANCELLED')
        WHEN 'WAITING_IO' THEN NEW.status IN ('RUNNING','BLOCKED','CANCELLED')
        WHEN 'BLOCKED' THEN NEW.status IN ('QUEUED','CANCELLED')
        WHEN 'CHECKPOINTED' THEN NEW.status IN ('QUEUED','RUNNING','CANCELLED')
        WHEN 'RESULT_COMMITTED' THEN NEW.status IN ('VERIFIED','QUARANTINED','NEEDS_REVIEW')
        WHEN 'VERIFIED' THEN NEW.status IN ('ACCEPTED','REJECTED','NEEDS_REVIEW')
        WHEN 'NEEDS_REVIEW' THEN NEW.status IN ('ACCEPTED','REJECTED','QUARANTINED')
        ELSE false END;
    IF NOT ok THEN RAISE EXCEPTION 'invalid task transition: % -> %', OLD.status, NEW.status; END IF;
    RETURN NEW;
END;
$$;
